# Generated by Django 3.2.24 on 2024-09-24 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ouedkniss', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Client',
        ),
    ]
