# Generated by Django 5.1.1 on 2024-09-25 22:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ouedkniss', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paiement',
            name='confirmation_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ouedkniss.order'),
        ),
    ]
